#!/bin/bash

title="Music"
widthpercent=50

typeset -A menu
menu=(
    [Steam]="steam-native"
    [Risk of Rain 2]="steam steam://rungameid/632360"
    [Itch]="itch"
    [Minecraft]="minecraft-launcher"
    [Beat Hazzard Ultra]="~/Documents/FloatingApps/BeatHazardUltra/BeatHazard.exe"
    [Intake]="~/Documents/FloatingApps/Intake_Win_1382564523/intake.sh"
    [Vectagon]="~/Documents/FloatingApps/VectagonLinux/Linux.x86"
    [Pixel Dungeon]="java -jar /home/vega/.config/itch/apps/pixel-dungeon/desktop-1.7.2a-1.jar"
)
menu_nrows=${#menu[@]}

typeset -A colors
colors=(
    [-color-window]="#000000, #ffffff, #ffffff"
    [-color-normal]="#ffffff, #000000, #eee8d5, #272727, #ffffff"
    [-color-active]="#fdf6e3, #268bd2, #eee8d5, #268bd2, #fdf6e3"
    [-color-urgent]="#fdf6e3, #dc322f, #eee8d5, #dc322f, #fdf6e3"
)